### ISSUE TITLE
Missing h5ad file in 3D reconstruction

### ISSUE THREAD

**Issue by fym0503** [aristoteleo/spateo-tutorials#3]
In 5_tdr/3D reconstruction.ipynb, The provided file here is missing
`adata = st.sample_data.drosophila(filename="E7-9h_cellbin.h5ad")
`
Traceback (most recent call last):
  File "/mnt/data/aim/fanyimin/projects/spateo-tutorials/5_tdr/3D Reconstruction.py", line 33, in <module>
    adata = st.sample_data.drosophila(filename="E7-9h_cellbin.h5ad")
  File "/mnt/data/aim/fanyimin/projects/spateo-release/spateo/sample_data.py", line 118, in drosophila
    adata = get_adata(url=url_dict[filename], filename=filename, dir_name=dir_name)
KeyError: 'E7-9h_cellbin.h5ad'

**Comment by matthieuheitz** [comment]
I would also be interested in having this file. 
Where can we access the timepoints collected in Spateo's publication? 
[Wang et al.](https://www.cell.com/developmental-cell/pdf/S1534-5807(22)00246-5.pdf) provide E14-16 and E16-18, where can we access E7-9 and E9-10?
Thank you!

**Comment by matthieuheitz** [comment]
Oh I just saw this: https://github.com/aristoteleo/spateo-release/issues/201#issuecomment-1701952965
Let us know when the paper is published then.
Thanks.

**Comment by HLL-1** [comment]
Waiting for the data update, thank you very much!

**Comment by hutaobo** [comment]
When will the data be updated?

**Comment by NMiyajima4611** [comment]
I've downloaded the data without specifying a filename.
adata = st.sample_data.drosophila()
adata.uns["__type"] = "UMI"
adata

|-----> Downloading data to ./data\E7-9h_cellbin_tdr_v2.h5ad
https://www.dropbox.com/s/bvstb3en5kc6wui/E7-9h_cellbin_tdr_v2.h5ad?dl=1
|-----> [download] in progress: 100.0000%
|-----> [download] finished [1719.0319s]
AnnData object with n_obs × n_vars = 25921 × 8136
    obs: 'area', 'slices', 'nGenes', 'nCounts', 'pMito', 'nMito', 'pass_basic_filter', 'scc', 'auto_anno', 'anno_cell_type', 'anno_tissue', 'anno_germ_layer', 'actual_stage', 'Size_Factor', 'initial_cell_size'
    uns: 'PCs', '__type', 'auto_anno_result', 'dendrogram_anno_cell_type', 'dendrogram_anno_germ_layer', 'dendrogram_anno_tissue', 'explained_variance_ratio_', 'latter_models_align', 'neighbors', 'pca_mean', 'pca_valid_ind', 'pearson_X_neighbors', 'pp', 'rank_genes_groups', 'rank_genes_groups_anno_cell_type', 'rank_genes_groups_anno_germ_layer', 'rank_genes_groups_anno_tissue', 'scc', 'spatial'
    obsm: '3d_align_spatial', 'align_spatial', 'bbox', 'before_3d_align_spatial', 'contour', 'pearson_X_pca', 'pearson_X_umap', 'spatial', 'spliced', 'tdr_spatial', 'unspliced'
    layers: 'counts_X', 'log1p_X', 'pearson_X', 'spliced', 'unspliced'

The default file name seems to be 'E7-9h_cellbin_tdr_v2.h5ad'.
According to the source code, the available file names are 
                * ``E7-9h_cellbin_tdr_v1.h5ad``
                * ``E7-9h_cellbin_tdr_v2.h5ad``
                * ``E7-9h_cellbin_tdr_v2_midgut.h5ad``
                * ``E7-9h_cellbin_tdr_v3_midgut.h5ad``
                * ``E7-9h_cellbin_h5ad.zip``
                * ``E7-9h_bin20_h5ad.zip``
                * ``E9-10h_cellbin_tdr_v1.h5ad``
                * ``E9-10h_cellbin_tdr_v2.h5ad``
                * ``E9-10h_cellbin_tdr_v2_midgut.h5ad``
                * ``E9-10h_cellbin_tdr_v2_CNS.h5ad``
